#!/bin/sh

i200='🫂'
i50='💖'
i10='✨'
i5='🥺'
i1=','
i0='❤️'
bss='👉'
bse='👈'

buf() {
	char="${l%"${l#?}"}"
	buf="$buf$char"

	case $buf in
	"$i0")
		printf '\0'
		l="${l#?}"
		sum=0
		buf=''
		return
		# continue
		;;
	"$i200")
		buf=
		: $((sum+=200))
		;;
	"$i50")
		buf=
		: $((sum+=50))
		;;
	"$i10")
		buf=
		: $((sum+=10))
		;;
	"$i5")
		buf=
		: $((sum+=5))
		;;
	"$i1")
		buf=
		: $((sum+=1))
		;;
	"$bss")
		printf "\\$(printf '%o' "$sum")"
		sum=0
		buf=
		;;
	"$bse")
		buf=
		;;
	esac
	l="${l#?}"
}

ch() {
	for i in "$bse" "$bss" "$i0" "$i200" "$i50" "$i10" \
					"$i5" "$i1"; do
		[ "${l%"${l#"$i"}"}" != "$i" ] &&
			continue
		case $i in
		"$bse") ;;
		"$bss")
			printf "\\$(printf '%o' "$sum")"
			sum=0
			;;
		"$i0")
			printf '\0'
			sum=0
			;;
		"$i200") : $((sum+=200)) ;;
		"$i50") : $((sum+=50)) ;;
		"$i10") : $((sum+=10)) ;;
		"$i5") : $((sum+=5)) ;;
		"$i1") : $((sum+=1)) ;;
		esac
		l="${l#"$i"}"
		break
	done
}

sum=0
while read -r l || [ -n "$l" ]; do
	while [ -n "$l" ]; do
		buf
	done
done
