#!/bin/sh
# Look for correct character and decode

i200='🫂'
i50='💖'
i10='✨'
i5='🥺'
i1=','
i0='❤️'
bss='👉'
bse='👈'
sum=0

while read -r l; do
	while [ -n "$l" ]; do
		for i in "$bse" "$bss" "$i0" "$i200" "$i50" "$i10" \
						"$i5" "$i1"; do
			[ "${l%"${l#"$i"}"}" != "$i" ] &&
				continue
			case $i in
			"$bse") ;;
			"$bss")
				printf "\\$(printf '%o' "$sum")"
				sum=0
				;;
			"$i0")
				printf '\0'
				sum=0
				;;
			"$i200") : $((sum+=200)) ;;
			"$i50") : $((sum+=50)) ;;
			"$i10") : $((sum+=10)) ;;
			"$i5") : $((sum+=5)) ;;
			"$i1") : $((sum+=1)) ;;
			esac
			l="${l#"$i"}"
			break
		done
	done
done
